import { describe, it, expect } from "vitest";
import {
  MasterFitnessStateSchema,
  Layer0SafetySchema,
  Layer1UserProfileSchema,
  Layer2PeriodizationSchema,
  Layer3ReadinessSchema,
  Layer4SessionMetaSchema,
  Layer5ExecutionSchema,
  Layer7ContextSchema,
  Layer8MathOverloadSchema,
  Layer9ExecutionCoachSchema,
} from "../schemas/fitness";

describe("10-Layer Master Fitness State Schema", () => {
  it("should validate a complete master fitness state payload", () => {
    const validState = {
      layer0_safety: {
        hasAcutePain: false,
        painSeverity: 0,
        painSensation: "none",
        jointCompromised: false,
        structuralFailure: false,
        dizzinessOrFaintness: false,
        arbitrationDecision: "MAINTAIN",
        requiresImmediateCooldown: false,
      },
      layer1_userProfile: {
        id: crypto.randomUUID(),
        name: "Muhamad",
        age: 27,
        sex: "male",
        bodyWeightKg: 82.5,
        heightCm: 178,
        trainingAge: "intermediate",
        baselineLifts: {
          squat1RM: 140,
          benchPress1RM: 105,
          deadlift1RM: 180,
          overheadPress1RM: 70,
          barbellRow1RM: 90,
          pullUp1RM: 35,
        },
        injuryHistoryNotes: ["Mild left patellar tendinopathy 2024"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      layer2_periodization: {
        primaryGoal: "hypertrophy",
        currentMesocyclePhase: "accumulation",
        mesocycleWeek: 3,
        totalMesocycleWeeks: 6,
        targetWeeklyFrequency: 4,
        targetRpeRange: [7, 9],
        deloadScheduled: false,
      },
      layer3_readiness: {
        sleepHours: 7.5,
        sleepQualityScore: 8,
        cnsFatigueScore: 3,
        systemicSorenessScore: 2,
        stressRating: 4,
        nutritionHydrationScore: 8,
        sorenessByMuscleGroup: { chest: 2, quads: 1 },
        readinessMultiplier: 1.0,
        downRegulateActive: false,
      },
      layer4_sessionMeta: {
        sessionId: crypto.randomUUID(),
        userId: crypto.randomUUID(),
        sessionName: "Upper Push Hypertrophy",
        sessionType: "upper",
        status: "in_progress",
        startedAt: new Date().toISOString(),
        elapsedMinutes: 25,
      },
      layer5_execution: {
        exercises: [
          {
            exerciseId: crypto.randomUUID(),
            exerciseName: "Barbell Bench Press",
            movementPattern: "horizontal_push",
            equipmentType: "barbell",
            orderIndex: 0,
            sets: [
              {
                setId: crypto.randomUUID(),
                setIndex: 0,
                setType: "working",
                weightKg: 90,
                reps: 8,
                targetReps: 8,
                rpe: 8,
                rir: 2,
                tempo: "3-0-1-0",
                restSeconds: 120,
                completedAt: new Date().toISOString(),
              },
            ],
          },
        ],
        totalSetsCompleted: 1,
        totalRepsCompleted: 8,
        totalTonnageKg: 720,
      },
      layer7_context: {
        timeRemainingMinutes: 45,
        isTimeConstrained: false,
        equipmentStatus: "available",
        gymCongestionLevel: "moderate",
        allowSupersets: false,
      },
      layer8_mathOverload: {
        estimated1RMBrzycki: 111.4,
        volumeLoadTonnage: 720,
        estimatedCaloriesBurned: 95,
        qualifiesForOverload: true,
        recommendedAction: "INCREMENT_LOAD",
        recommendedLoadDeltaKg: 2.5,
        recommendedRepsDelta: 0,
        arbitrationOverrideApplied: false,
      },
      layer9_coachDirective: {
        urgency: "EXECUTE",
        directiveText: "Clean 8 reps at RPE 8. Add 2.5kg next set. Rest 2 minutes.",
        wordCount: 13,
        cueCategory: "load_adjustment",
        timestamp: new Date().toISOString(),
      },
      schemaVersion: "1.0.0",
      lastStateSync: new Date().toISOString(),
    };

    const parsed = MasterFitnessStateSchema.safeParse(validState);
    if (!parsed.success) {
      console.error(JSON.stringify(parsed.error.issues, null, 2));
    }
    expect(parsed.success).toBe(true);
  });

  it("should reject coach directives exceeding 30 words", () => {
    const longText =
      "This is a very long coaching directive that is meant to test the strict thirty word limit constraint and make sure that any long verbose response generated by the language model gets immediately flagged and rejected by the Zod runtime validation engine.";
    
    const wordCount = longText.trim().split(/\s+/).filter(Boolean).length;
    expect(wordCount).toBeGreaterThan(30);

    const parsed = Layer9ExecutionCoachSchema.safeParse({
      urgency: "EXECUTE",
      directiveText: longText,
      wordCount: wordCount,
      cueCategory: "technique",
      timestamp: new Date().toISOString(),
    });

    expect(parsed.success).toBe(false);
  });

  it("should enforce Layer 0 acute pain schema attributes", () => {
    const painPayload = {
      hasAcutePain: true,
      painSite: "Right Shoulder",
      painSeverity: 8,
      painSensation: "sharp",
      jointCompromised: true,
      structuralFailure: false,
      dizzinessOrFaintness: false,
      arbitrationDecision: "HARD_STOP",
      abortReason: "Acute sharp joint pain reported in right shoulder during bench press.",
      requiresImmediateCooldown: true,
    };

    const parsed = Layer0SafetySchema.safeParse(painPayload);
    expect(parsed.success).toBe(true);
    if (parsed.success) {
      expect(parsed.data.arbitrationDecision).toBe("HARD_STOP");
      expect(parsed.data.hasAcutePain).toBe(true);
    }
  });
});
